name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Corre cada día a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Generate Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Ruiz-z
          outputs: |
            ./output/pacman-contribution-graph.svg?palette=github-dark
            ./output/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push SVG to output branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generate Pacman contribution graph"
          add: "output/pacman-contribution-graph*.svg"
